environment: "hanxux"
cloud: azurecloud
product: "local"
dns:
  domain: "azure.autoheim.net"
  subscription_id: "287b9fb1-557e-4f1a-9c99-1a5e1a322cee"
  resource_group_name: "rg-es-identity-dns-westeurope"
commoninfra:
  kafka:
    name: kafka
    zoneredundant: "false"
    kafka_controller_resources:
      requests:
        cpu: 300m
        memory: 200Mi
      limits:
        cpu: 600m
        memory: 2Gi
    kafka_resources:
      requests:
        ## see https://github.com/strimzi/strimzi-kafka-bridge/issues/731
        cpu: 600m
        memory: 200Mi
      limits:
        cpu: 1200m
        memory: 4Gi
    version: 3.7.1
    replicas: 3
    storage:
      type: persistent-claim
      size: "1Gi"
      class: sc-nfs

