{
 "title": "Logs from Loki",
 "description": "Logs from loki",
 "tags": [
  "testapps",
  "test-delivery"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "logs",
   "type": "logs",
   "description": "Logs from the loki.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{namespace=\"testapps\", container=\"compile\"} |= ``"
    }
   ]
  },
  {
   "title": "tile-delivery logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{namespace=\"testapps\", container=\"test-delivery\"} |= ``"
    }
   ]
  },
  {
   "title": "transport-agent-carfleet logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{namespace=\"testapps\", container=\"transport-agent-carfleet\"} |= ``"
    }
   ]
  },
  {
   "title": "car-tile-consumer",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "{namespace=\"carfleettest\", container=\"car-tile-consumer\"} |= ``"
    }
   ]
  },
  {
   "title": "source-test-download logs",
   "type": "logs",
   "description": "Last 15 minutes of source-test-download applicaiton logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "{namespace=\"testapps\", container=\"source-test-download\"} |= ``"
    }
   ]
  },
  {
   "title": "cloud-event-operator logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "{namespace=\"testapps\", container=\"cloud-event-operator\"} |= ``"
    }
   ]
  }
 ]
}