acls:
  - resource:
      name: '*'
      patternType: literal
      type: topic
    operations:
      - Read
      - Describe
      - DescribeConfigs

  - resource:
      name: '*'
      patternType: literal
      type: group
    operations:
      - Describe
      - Read
